#!/bin/bash
if [[ -d ~/Abhay ]]
then
	echo "The folder already exists"
else
	mkdir ~/Abhay
fi

cd ~/Abhay
if [[ -d ~/Abhay/cryptage ]];
then
	echo "The folder is already cloned"
else
	git clone https://github.com/AbhayGunputh/cryptage.git
fi

cd ~/Abhay/cryptage/Crypt/src/
#sudo chmod u+x crypt.sh
#sudo ./crypt.sh
#sudo chmod u+x decrypt.sh
#sudo ./decrypt.sh

#To give permission and launch the cryption and decryption
sudo cp -f ~/Abhay/cryptage/Crypt/src/crypt.sh ~/Abhay/crypt.sh
sudo chmod u+x crypt.sh
sudo cp -f ~/Abhay/cryptage/Crypt/src/crypt.sh ~/Abhay/decrypt.sh
sudo chmod u+x decrypt.sh

#copy the service to systemd
sudo cp -f ~/Abhay/cryptage/Crypt/src/crypt.service /etc/systemd/system/crypt.service
sudo cp -f ~/Abhay/cryptage/Crypt/src/decrypt.service /etc/systemd/system/decrypt.service

#Launch service
sudo systemctl daemon-reload
sudo systemctl enable crypt.service
sudo systemctl start crypt.service
sudo systemctl daemon-reload
sudo systemctl enable decrypt.service
sudo systemctl start decrypt.service

echo "Installation Completed!"
